name: Validate

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  validate-python:
    name: Validate Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Home Assistant
        run: |
          pip install homeassistant

      - name: Validate manifest
        run: |
          python -c "import json; json.load(open('custom_components/nidia_magic_composer/manifest.json'))"

      - name: Check Python syntax
        run: |
          python -m py_compile custom_components/nidia_magic_composer/*.py

  validate-frontend:
    name: Validate Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Type check
        run: |
          cd frontend
          npm run type-check

      - name: Lint
        run: |
          cd frontend
          npm run lint

      - name: Build
        run: |
          cd frontend
          npm run build
